-- Open Forms 초기 스키마
-- docs/04-db-design.md 의 테이블 정의서와 1:1 일치.
-- PostgreSQL / H2(PostgreSQL 호환 모드) 양쪽에서 동작하는 이식 가능한 DDL 사용.
--
-- 감사 컬럼(created_by/created_at/updated_by/updated_at)은 그 값이 새로운 정보를 담는
-- 곳에만 둡니다: users·forms 는 4종, responses 는 제출 후 불변이므로 created_* 2종만.
-- 상위에 종속되어 함께 생성·삭제되는 테이블(questions·question_options·answers)은
-- 감사값이 상위와 항상 같으므로 제외합니다.
-- 생성자/변경자는 로그인 시 이메일, 비로그인 시 'ANONYMOUS' 를 담는 VARCHAR 입니다.

-- ── users: 폼 제작자 계정 ──
-- id 는 UUID 입니다(다른 테이블은 BIGINT). 순차 PK 는 식별자로부터 가입자 수를
-- 추정할 수 있게 하므로, 계정 식별자에 한해 이를 차단합니다. users 는 저볼륨이라
-- UUID 의 인덱스 지역성 비용이 무시할 수준입니다. 값은 애플리케이션에서
-- Hibernate @UuidGenerator(style = VERSION_7) 로 생성하며(DB 기본값 없음),
-- 시간 정렬 UUID 라 B-tree 삽입 지역성도 유지됩니다.
CREATE TABLE users (
    id            UUID         NOT NULL PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(100) NOT NULL,
    created_by    VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_by    VARCHAR(100) NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ── forms: 설문 폼 ──
CREATE TABLE forms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID          NOT NULL,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)   NOT NULL,
    slug        VARCHAR(64)   NOT NULL,
    created_by  VARCHAR(100)  NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_by  VARCHAR(100)  NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT uk_forms_slug UNIQUE (slug),
    CONSTRAINT fk_forms_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_forms_user_id ON forms (user_id);
CREATE INDEX ix_forms_user_status ON forms (user_id, status);

-- ── questions: 질문 ──
-- type: SHORT_TEXT / LONG_TEXT / SINGLE_CHOICE / DROPDOWN / MULTIPLE_CHOICE
--       / RATING / NUMBER / DATE / TIME (애플리케이션 Enum 으로 값 무결성 보장)
-- min_value·max_value: RATING/NUMBER 의 허용 범위. 그 외 타입에서는 NULL.
CREATE TABLE questions (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id   BIGINT       NOT NULL,
    type      VARCHAR(20)  NOT NULL,
    title     VARCHAR(500) NOT NULL,
    required  BOOLEAN      NOT NULL,
    position  INT          NOT NULL,
    min_value INT,
    max_value INT,
    CONSTRAINT fk_questions_form FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE
);
CREATE INDEX ix_questions_form_id ON questions (form_id);

-- ── question_options: 선택지 ──
CREATE TABLE question_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT       NOT NULL,
    label       VARCHAR(255) NOT NULL,
    position    INT          NOT NULL,
    CONSTRAINT fk_options_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);
CREATE INDEX ix_question_options_question_id ON question_options (question_id);

-- ── responses: 응답 제출 1건 (익명, 제출 후 불변) ──
-- created_at 이 곧 제출 시각입니다(별도 submitted_at 을 두면 의미가 중복됩니다).
-- created_by 는 응답자이며 익명 제출이면 'ANONYMOUS' 입니다.
-- 응답은 제출 후 수정할 수 없으므로 updated_by/updated_at 을 두지 않습니다
-- (수정이 없으면 두 컬럼은 영구히 created_* 와 같은 값이 됩니다).
CREATE TABLE responses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id    BIGINT       NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_responses_form FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE
);
CREATE INDEX ix_responses_form_created ON responses (form_id, created_at);

-- ── answers: 제출된 값 1건 ──
-- 한 행이 곧 "제출된 값 하나"입니다(질문당 1행이 아닙니다).
--   · 값 입력형(단답/장문/평점/숫자/날짜/시간): 해당 값 컬럼 하나만 채운 1행
--   · 택1형(SINGLE_CHOICE/DROPDOWN): option_id 만 채운 1행
--   · 체크박스(MULTIPLE_CHOICE): 고른 선택지 개수만큼 행(각 행에 option_id 하나)
-- 조인 테이블(answer_options) 대신 option_id 를 직접 두어, 가장 흔한 택1형이
-- 행 하나로 저장되고 선택지별 집계가 조인 없이 처리됩니다.
CREATE TABLE answers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id  BIGINT NOT NULL,
    question_id  BIGINT NOT NULL,
    option_id    BIGINT,
    text_value   TEXT,
    number_value INT,
    date_value   DATE,
    time_value   TIME,
    -- 폼 삭제 시 연쇄 삭제 경로가 responses→answers 와 questions→answers 두 갈래이므로
    -- question_id·option_id 에도 CASCADE 가 필요합니다. 없으면 어느 갈래가 먼저 지워지든
    -- 남은 answers 가 참조 무결성 검사에 걸려 폼 삭제 자체가 실패합니다.
    CONSTRAINT fk_answers_response FOREIGN KEY (response_id) REFERENCES responses (id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_option FOREIGN KEY (option_id) REFERENCES question_options (id) ON DELETE CASCADE
);
CREATE INDEX ix_answers_response_id ON answers (response_id);
-- (question_id, option_id) 복합: 최좌측 프리픽스로 "질문별 응답 분포"(question_id 필터)를
-- 커버하면서 "선택지별 선택 수"(option_id 그룹핑)까지 한 인덱스로 처리합니다.
CREATE INDEX ix_answers_question_option ON answers (question_id, option_id);
