-- API 호출 이력 (디버깅·추적용 인프라 테이블)
-- 도메인 7테이블(ERD)과 별개인 운영 로그입니다. 메타데이터만 저장하며 요청/응답 본문·비밀번호·
-- JWT 는 저장하지 않습니다. 매 요청마다 비동기로 1행씩 적재됩니다(ApiCallLogWriter).
-- PostgreSQL / H2(PostgreSQL 호환 모드) 양쪽에서 동작하는 이식 가능한 DDL 사용.
--
-- principal: 호출 주체를 감사 컬럼(created_by)과 동일한 소스로 기록합니다 — 인증 시 이메일,
--   비인증이면 NULL. user_id(UUID FK) 대신 문자열을 쓰는 이유는 매 요청 조회를 없애고
--   이 인프라 로그가 user 테이블에 의존하지 않게 하기 위함입니다.
CREATE TABLE api_call_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id    VARCHAR(64)  NOT NULL,
    method      VARCHAR(10)  NOT NULL,
    path        VARCHAR(500) NOT NULL,
    status      INT          NOT NULL,
    principal   VARCHAR(100),
    duration_ms BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);
-- traceId 로 한 요청의 이력을 조회, created_at 으로 기간별 조회를 커버합니다.
CREATE INDEX ix_api_call_logs_trace_id   ON api_call_logs (trace_id);
CREATE INDEX ix_api_call_logs_created_at ON api_call_logs (created_at);
