-- 리프레시 토큰: 액세스 토큰(1시간) 만료 시 재로그인 없이 갱신하기 위한 자격증명입니다.
--
-- 액세스 토큰은 무상태 JWT 라 서명만 맞으면 만료 전까지 폐기할 수 없습니다. 그래서 수명을 짧게 두고,
-- 대신 "갱신할 권리"를 이 테이블에 상태로 남깁니다. 상태가 DB 에 있으므로 로그아웃·유출 대응 시
-- 서버가 실제로 무효화할 수 있습니다(무상태 JWT 만으로는 불가능한 일입니다).
--
-- 토큰 원문은 저장하지 않고 SHA-256 해시만 남깁니다. DB 가 유출되어도 그 값으로 갱신할 수 없게 하기
-- 위함입니다. 비밀번호와 달리 BCrypt 를 쓰지 않는 이유는 **해시로 조회**해야 하기 때문입니다 —
-- BCrypt 는 행마다 salt 가 달라 동등 비교 조회가 불가능해 전수 스캔이 됩니다. 원문이 256비트
-- 난수(SecureRandom)라 사전 공격 대상이 아니므로 key stretching 이 필요 없습니다.
--
-- 사용한 토큰을 지우지 않고 revoked_at 으로 남기는 것은 **재사용 탐지**를 위해서입니다. 이미 회전된
-- 토큰이 다시 제시되면 사본이 돌아다닌다는 뜻이므로, 그 사용자의 토큰을 전부 폐기합니다. 행을 지우면
-- "회전된 토큰"과 "존재한 적 없는 토큰"을 구분할 수 없어 이 탐지가 불가능해집니다.
--
-- 감사 4종 컬럼(created_by/at·updated_by/at)은 두지 않습니다. 생성 주체는 언제나 토큰 소유자 본인이고
-- 시각은 issued_at·revoked_at 이 이미 담고 있어, 감사 컬럼이 새로운 정보를 더하지 않기 때문입니다
-- (V1 의 감사 컬럼 부여 기준과 같은 논리).
CREATE TABLE refresh_tokens (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID        NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    issued_at  TIMESTAMP   NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    revoked_at TIMESTAMP,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
-- 재사용이 탐지되면 해당 사용자의 토큰을 한 번에 폐기하므로 user_id 로 조회합니다.
-- (토큰 단건 조회는 uk_refresh_tokens_hash 유니크 인덱스가 이미 커버합니다.)
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
